// Configuration constants for the blog processing scripts

export const FOLDERS_TO_PROCESS = [
  "blogs/[1]-cross-border",
  "blogs/[2]-incoterms",
  "blogs/[3]-ftl-groupage",
  "blogs/[4]-transit-times",
  "blogs/[5]-fuel-surcharges",
  "blogs/[6]-seasonality",
  "blogs/[7]-packaging-palletization",
  "blogs/[8]-freight-forwarder",
  "blogs/[9]-damage-claims",
  "blogs/[10]-sustainability",
  "blogs/[11]-ai-route-optimization",
  "blogs/[12]-digital-forwarding",
  "blogs/[13]-cabotage-rules",
  "blogs/[14]-low-emission-zones",
  "blogs/[15]-cold-chain",
  "blogs/[16]-post-brexit",
  "blogs/[17]-paperless-freight",
  "blogs/[18]-intermodal-transport",
  "blogs/[19]-driver-shortages",
  "blogs/[20]-reverse-logistics",
  "blogs/[21]-last-mile",
  "blogs/[22]-warehouse-automation",
];
